name: easy_cv
description: Easy CV

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # architecture
  scoped_model: ^0.3.0
  dio: ^3.0.7

  # firebase
  firebase_auth: ^0.15.3
  cloud_firestore: ^0.13.5

  # assets
  r_flutter: ^0.5.0

  # uis
  responsive_builder: ^0.1.5
  cached_network_image: ^2.0.0
  shimmer: ^1.0.1
  fluttertoast: ^4.0.1
  flutter_datetime_picker: ^1.3.8

  # utils
  url_launcher: ^5.4.1
  share: ^0.6.4
  image_picker: ^0.6.5+3

  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/profile.png

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway_regular.otf
        - asset: assets/fonts/raleway_italic.otf
          style: italic
        - asset: assets/fonts/raleway_bold.otf
          weight: 700
