name: easy_cv
description: Easy CV

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # architecture
  scoped_model: ^0.3.0
  dio: ^3.0.7

  # firebase
  firebase_auth: ^0.15.3
  cloud_firestore: ^0.13.2+3

  # assets
  r_flutter: ^0.5.0

  # uis
  cached_network_image: ^2.0.0
  shimmer: ^1.0.1

  # utils
  url_launcher: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
